### PR TITLE
Fix flashing home direction arrow in its default position

### LINKED ISSUE #2207: Home direction arrow flashes due to overlapping with AHI
By default, the home direction arrow is positioned in an area which the AHI uses too. This causes flashing since we never redraw the whole screen while the aircraft is armed. While we could move the default position one row down, it seems a better solution would be to not clear the centre bottom area of the AHI, since the line is never drawn there. See the attached images for reference.

screen shot 2017-09-25 at 21 09 44
screen shot 2017-09-25 at 21 10 03

### PR DESCRIPTION
**Pull request by fiam**
Don't erase the center of the last row in the AHI. This allows
the home direction arrow to be positioned just below the AHI in
its unused area.

Fixes #2207

Kudos to @giacomo892 for noticing the problem

### CODE REVIEW

**Comment by fiam** [comment]
Just added a second commit on top which optimises the AHI drawing dramatically by avoiding writing the whole AHI area on each refresh. See the comments in the code for the details.

Here are a couple graphs before an after (debug[0] = µs spent on `max7456DrawScreenPartial()`, debug[1] = chars sent to MAX7456, debug[2] = bytes sent to MAX7456) when the AHI is being drawn repeatedly on the same position. 

## Before

screen shot 2017-09-25 at 22 33 22

## After

screen shot 2017-09-25 at 22 45 26

File: src/main/io/osd.c [hunk 1]
```diff
@@ -646,13 +653,34 @@ static bool osdDrawSingleElement(uint8_t item)
...
+                // at a different Y coordinate. The video buffer will take care
+                // of ignoring the write if we're writing the same character
+                // at the same Y coordinate.
+                //
+                // Note that this implementation leaves an untouched character
+                // in the bottom center of the indicator, which allows positioning
+                // the home directorion indicator there.
                 const int y = (-rollAngle * x) / 64 - pitchAngle;
+                int wx = x + 4; // map the -4 to the 1st element in the writtenY array
+                int pwy = writtenY[wx]; // previously written Y at this X value
```
Comment (digitalentity) [inline src/main/io/osd.c:667]: Why using a new variable here? Compiler (usually) is smart enough to optimize array dereferencing.

Comment (fiam) [reply src/main/io/osd.c:667]: I just put it in a variable for clarity (same as `ch` a few lines down). I haven't checked the assembly, but I'd expect the compiler to generate the same code.

Comment (fiam) [reply src/main/io/osd.c:667]: Just checked, exactly the same assembly.

**Comment by fiam** [comment]
Just did some profiling and this also brings down draw time for OSD_ARTIFICIAL_HORIZON from constant 50µs to 8µs when idle and 15µs when changing quickly.
