### PR TITLE
Fix orientation of the drivers for AK8963, AK8975 and MPU9250 MAGs

### LINKED ISSUE #3434: Alignment for AK8975, AK8963 (and MPU9250, which includes an AK8963) seems incorrect
Update: Turns out this somewhat works right now because we're ignoring the Z axis of the magnetometer, so the correct X/Y alignment can be achieve by flipping the mag alignment (which results in inverted Z axis, but works). Postponing to 2.1.

Reported in comments for  #3413, #3288 and #3398

### LINKED ISSUE #3438: F3 EVO default compass direction of MPU9250 is not correct
F3 EVO FC default compass direction of MPU9250 is not correct in Inav 1.9, and it must be set to flip90CW.And the accelerometer, the gyro is not needed

### PR DESCRIPTION
**Pull request by fiam**
Due to the unsual axis definition of the AKxxxx MAGs (the +Y axis
is 90ºCW from the +X axis when +Z points up), the driver needs to
invert e.g. X and Z, then rotate rather than inverting all of
X, Y and Z like it was doing.

It seems this bug was introduced in 3d024c6f3 back in November,
between 1.8 and 1.9 and some targets were written or updated in the
meantime assuming the driver was correct and thus have incorrect mag
alignments. I've tried to fix them all, but I don't have all these
boards and while ones with the MP9250 are obvious (assumming the
acc/gyro orientation is right, the mag orientation can be derived
from it), some of them have AK8963 or AK8975 which might be
oriented differently than the acc/gyro.

Fixes #3438
Fixes #3434

### CODE REVIEW

**Comment by fiam** [comment]
Compiled hex files for affected targets.

[TEST_3434.zip](https://github.com/iNavFlight/inav/files/2134498/TEST_3434.zip)

**Comment by fiam** [comment]
@zipray, @rb1205, @tootomthumb, @gbine, @robertha64 Please, give this a try. Let me know if you needs builds for other targets that I might have missed.

**Comment by tootomthumb** [comment]
@fiam Sorry for taking so long to respond, I don't normally get the chance to try things out until the weekends.

I couldnt find a build for the Matek 405 (using the AK8975) in your zip file, so I tried to build it myself. I'm not sure if I built the correct .hex but can say it has definitely changed stuff. Where my previous configuration had all the XYZs lined up and the heading wrong by 180 degrees, now the heading is correct but the X axis is inverted relative to accelerometer movements.

Keep in mind my AK8975 is integrated with a GPS antenna so there is no physical connection between my magnetometer and FC so there could be user error involved!

Anyways thanks again for helping out!

**Comment by tootomthumb** [comment]
@fiam please ask if you need any other data or need me to test any code.

File: src/main/drivers/compass/compass_ak8963.c [hunk 1]
```diff
@@ -139,7 +139,7 @@ static bool ak8963Read(magDev_t * mag)
     }
 
     mag->magADCRaw[X] = -parseMag(buf + 0, magGain[X]);
-    mag->magADCRaw[Y] = -parseMag(buf + 2, magGain[Y]);
+    mag->magADCRaw[Y] = parseMag(buf + 2, magGain[Y]);
```
Comment (digitalentity) [inline src/main/drivers/compass/compass_ak8963.c:142]: I think hardware driver should return data as listed in datasheet and thus no axis rotation should be applied at driver level - let `align_mag` parameter (and it's default value) handle the chip orientation.

Comment (digitalentity) [reply src/main/drivers/compass/compass_ak8963.c:142]: On the other hand AKxxxx is special - its "flipped" by default, Z-axis pointing downwards and it makes sense to rotate it so Z points up as in commonly used HMC and QMC mags.

**Comment by tootomthumb** [comment]
@zipray, @rb1205, @gbine, @robertha64 did the changes work for you?

**Comment by rb1205** [comment]
Unfortunately I lost my quad to the infamous disarm bug, can't test it right now.

**Comment by tootomthumb** [comment]
@rb1205 how did you fly with your magnetometer messed up?

I havent been off the ground for weeks....considering going back to Betaflight until this is sorted out.

**Comment by rb1205** [comment]
I downgraded to 1.8

**Comment by tootomthumb** [comment]
@rb1205 I couldnt use 1.8 because I found the cardinal points/planes (XYZ) of the accelerometer were aligned with the magnetometer the magnetometer was 180 degrees out (North was South).

Are you using the GPS functions with success or are you using things like the magnetometer for just orientation and FPV info?

**Comment by rb1205** [comment]
It uses mag and GPS to navigate a quad just fine. However, consider that I use the MPU9250 integrated in the SP3EVO board, not the AK8975 in the beitian.

**Comment by robertha64** [comment]
Hi, I could not test the change as using Omnibus target with separate AK8975 mag on Beitian GPS, precompiled targets did not include Omnibus. I downgraded to 1.8 for now and fly regardles of wrong orientation (did set alingment the way it pretend crucial directions) - but this work when horizontal only, when I pitch or roll the error increases - but still flyable but no missions.

**Comment by tootomthumb** [comment]
@robertha64 yeah so exactly same issue as myself on 1.8
@rb1205 thanks for the confirmation that you're currently flying without AK8975

**Comment by tootomthumb** [comment]
@fiam @digitalentity is there going to be any further progress on this or should I find a new GPS/Mag if I want to use INAV?

**Comment by digitalentity** [comment]
Oops, seems like we've forgotten about this one. @fiam can you rebase so we can merge it?

**Comment by fiam** [comment]
This turned out to not be that big of a problem, since the compasses are only incorrect in the Z axis sign, which right now is ignored by inav. I think we should postpone to 2.1.

**Comment by digitalentity** [comment]
@fiam it's ignored after being rotated to Earth frame - Z-axis sign doesn't matter only when aircraft is totally level.

**Comment by fiam** [comment]
@digitalentity Just rebased, but I don't think this has been tested enough to go into 2.0 final without going into an RC first. Maybe we can aim for a small 2.1 release and go for RC1 just after 2.0 is released?

**Comment by tootomthumb** [comment]
@fiam @digitalentity I'm running a Matek 405 STD with an AK8975 and very happy to test whatever you want to throw at me!

Also, although I dont have a clue how the Z axis is used, I can confirm things were definitely messed up!

**Comment by tootomthumb** [comment]
Sorry for the newb question, but is there anything I can test?

**Comment by robertha64** [comment]
I think changes was merged to dev branch, unless you can compile hex for your target you need to wait for next release (full or RC).

**Comment by robertha64** [comment]
I am waiting to test too.

**Comment by tootomthumb** [comment]
Thanks for the clarification. I've compiled it before so happy to try it again. If I manage to do it what target do you need?

**Comment by robertha64** [comment]
Omnibus (F3)

Thanks

**Comment by robertha64** [comment]
By the way I want to share how I believe found the mag driver is probably not correct:
Idid try fly 200meters directly to South in Poshold, then release the sticks, but copter itself did fly about 50 meters to East after sticks released and then return slowly to the point where sticks were released.
I have and idea why its behaved like this: As mag starts deviate when copter tilted (stick not centered), copter thought its flying West while commanded South so after stick release it wants to correct the error, but GPS did navigate to correct spot afterwards.

This issue I can repeat each flight, so looks like the best testing pattern.
Hope it makes sense.

**Comment by tootomthumb** [comment]
Yeah the results all depend on what you allow to be configured badly. For instance, I could get all the coordinate axes to be aligned correctly, but then the heading was off by 180. If I got the heading correct then any pitch or roll would cause erroneous heading changes. Point is, that until it is fixed it won't work!

I tried compiling the project but then got version 1.9 which was bugged, of course, but I cant quite remember how to download a specific dev version....

I'll try to do that again later today or tomorrow.

**Comment by robertha64** [comment]
I never did that, but you need to download this one ?
https://github.com/iNavFlight/inav/tree/development

**Comment by robertha64** [comment]
To be exact
https://github.com/iNavFlight/inav/tree/development/src/main
(in comment is mag orientation fix mentioned - 4days ago)

**Comment by tootomthumb** [comment]
@robertha64 it seemed to work for me and I could get stable (to pitch and roll) mag readings with the correct heading! Attached is the hex for the OMNIBUS, see if it works.

[inav_2.0.0_OMNIBUS.zip](https://github.com/iNavFlight/inav/files/2284136/inav_2.0.0_OMNIBUS.zip)

@fiam I'm hoping to try and fly this one over the weekend but I may be busy...if I manage to test it in a quad then I will post here. Whatever happens, thanks for all the help!

**Comment by robertha64** [comment]
@tootomthumb,  I did upload to my Omnibus, but did get red compass sign - it means compass did not get recognised even I choose AK8975 manually. The same configuration IS recognised on 1.8 nicely and "work" (with orientation error we know). Looks like also something else is broken in compass detection for Omnibus.

**Comment by robertha64** [comment]
Maybe I know why - AK8975 mag is NOT defined in inav / src / main / target / OMNIBUS / target.h.
omnibus mag

**Comment by robertha64** [comment]
Here is the same part from 1.8 - define USE_MAG_AK8975 is what I believe made my board working.
omnibus mag 1_8

**Comment by tootomthumb** [comment]
@robertha64 sorry, I tried to recompile after adding: "#define USE_MAG_AK8963" and "#define USE_MAG_AK8975" into the OMNIBUS target.h file but it then gives me compile errors like: "/src/main/sensors/compass.c:129: undefined reference to `ak8975Detect'"

I'm not a programmer so that's about all I can try....got to wait for one of the real contributors to chip in.

**Comment by robertha64** [comment]
@tootomthumb Thank you for try anyway, I did raise new issue just now.

**Comment by robertha64** [comment]
Strange is the support for AK8975 was fixed in
https://github.com/iNavFlight/inav/commit/38058a28b3b2dff5bed20fabeb0b253b056e0c02
inav ak8975 fix in common hw
in common_hardware.c
but this part of code is again missing in actual version
inav 2_0 commonc

**Comment by maRCnh33** [comment]
> Compiled hex files for affected targets.
> 
> [TEST_3434.zip](https://github.com/iNavFlight/inav/files/2134498/TEST_3434.zip)

can you please make a file for my FF F35 Board?? tnx a lot
