### PR TITLE
Do not show efficiency on osd when ground speed is below 1 m/s

### LINKED ISSUE #6467: Wh/km efficiency keep changing when aircraft is on the ground
## Current Behavior
When the aircraft is on the ground, and thus not flying, the Wh/km efficiency value on the OSD keep jumping around even though the indicated speed is zero. The mAh/km value correctly shows --- to indicate that this value cannot be calculated when speed is zero. 

https://user-images.githubusercontent.com/880421/103463025-85e04f00-4d29-11eb-9606-957e1f3fb189.mp4

## Steps to Reproduce

1. Put Wh/km efficiency on OSD
2. See that value is changing when aircraft is not flying

## Expected behavior
When speed is zero (or maybe better a low value), display --- Wh/km. 

## Additional context

---

- FC Board name and vendor: MATEK F765 Wing
- INAV version string: INAV/MATEKF765 2.6.0 Dec 29 2020 / 23:11:02 (d72b4649)

This is a custom firmware version to test some PR's but it is unlikely that these cause this bug.

### PR DESCRIPTION
**Pull request by avsaase**
Fixes #6467. I replaced the sanity checks for a reasonable efficiency (<999mAh/km and <999Wh/km) by an explicit check for a ground speed above 1m/s.

### CODE REVIEW

File: src/main/io/osd.c [hunk 1]
```diff
@@ -2993,6 +2991,19 @@ static void osdShowStats(void)
...
+                if (osdConfig()->stats_energy_unit == OSD_STATS_ENERGY_UNIT_MAH){
+                    buff[3] = SYM_MAH_KM_0;
+                    buff[4] = SYM_MAH_KM_1;
+                    buff[5] = '\0';
+                } else {
+                    buff[3] = SYM_WH_KM_0;
+                    buff[4] = SYM_WH_KM_1;
+                    buff[5] = '\0';
+                }
+            }
```
Comment (avsaase) [inline src/main/io/osd.c:3006]: This looks a bit unwieldy to me, but I can't think of a better way because the efficiency value does not have a fixed number of digits when using the `MAH` unit.

File: src/main/io/osd.c [hunk 2]
```diff
@@ -2982,7 +2980,7 @@ static void osdShowStats(void)
         displayWrite(osdDisplayPort, statValuesX, top++, buff);
 
         int32_t totalDistance = getTotalTravelDistance();
-        if (totalDistance > 0) {
+        if (STATE(GPS_FIX)) {
```
Comment (digitalentity) [inline src/main/io/osd.c]: Not sure this is a good idea. You may have landed w/o GPS fix, yet the efficincy data might still be be more-less accurate.

Comment (avsaase) [reply src/main/io/osd.c]: That's a good point, but max speed, max distance and traveled distance use the same check. Maybe change both to `feature(FEATURE_GPS)`?

Comment (digitalentity) [reply src/main/io/osd.c]: Sounds good!

Comment (avsaase) [reply src/main/io/osd.c]: Done.

**Review by digitalentity — APPROVED** [review]

**Comment by avsaase** [comment]
Thanks!
