### PR TITLE
Fix overflow in currentSensorToCentiamps()

### LINKED ISSUE #3124: Current sensor not showing correct above approx. 20 amp. on OSD / Telemetry
### Board and Version
INAV/OMNIBUS 1.9.1 Apr 21 2018 / 12:53:03 (03a5c1922) (Tricopter)
and also on
INAV/OMNIBUSF4V3 1.9.1 Apr 21 2018 / 13:13:58 (03a5c1922) (Flying Wing)

### Behavior

Current sensor indication on OSD / Telemetry seems to work just fine at low throttle, but above say 20 Amp, is suddenly start to show much lower (like 1/10 of the actual reading)

Both use an external APM power module current sensor,
Current sensors work just fine on iNav 1.8.0, as well as on pre-1.9.1 development builds.

In the blackbox log, it seems to work just fine, 
But it's not correct for high readings on OSD and not on Telemetry.
Also the mAh counter, is much slower (as if the current was really low).

#### Blackbox logs/Config (.ZIP) where problem occurs
https://pastebin.com/2PE39SX8 (for the tricopter).
[LOG00002.TXT](https://github.com/iNavFlight/inav/files/1948576/LOG00002.TXT)

(yes, I know, there is some vibration problem on the ACC, causing alt-hold problems, but that's not the issue here).

### PR DESCRIPTION
**Pull request by shellixyz**
Fixes #3124

### CODE REVIEW

File: src/main/sensors/battery.c [hunk 1]
```diff
@@ -108,7 +108,7 @@ uint16_t batteryAdcToVoltage(uint16_t src)
 
 int32_t currentSensorToCentiamps(uint16_t src)
 {
-    int32_t microvolts = ((uint32_t)src * ADCVREF * 1000) / 0xFFF - (int32_t)batteryConfig()->current.offset * 1000;
+    int32_t microvolts = ((uint32_t)src * ADCVREF * 100) / 0xFFF * 10 - (int32_t)batteryConfig()->current.offset * 1000;
```
Comment (digitalentity) [inline src/main/sensors/battery.c:111]: Good catch! I didn't realize that after a certain point multiplication result won't fit into 32 bits any more. Since `ADCVREF` is `3300` we are not loosing any percision with this change.

**Review by digitalentity — APPROVED** [review]
