### PR TITLE
Fix Nav Launch detection related bugs

### LINKED ISSUE #6427: Flight timer doesn't start until auto launch sequence ends
## Current Behavior
Basically the title. I have launch mode permanently enabled and use the the combined on/flight timer. When arming the fc, the timer switches from the on timer to the flight timer and resets to zero, but it doesn't start counting until the launch sequence ends.

## Steps to Reproduce

1. Launch plane with auto launch
2. Flight timer doesn't start until launch sequence ends

## Expected behavior
Flight timer starts when the fc is armed or even better, when the launch is detected.

## Additional context

---

- FC Board name and vendor: Matek F405-Wing
- INAV version string: # INAV/MATEKF405SE 2.6.0 Dec 15 2020 / 17:15:38 (8eb39862)

### PR DESCRIPTION
**Pull request by breadoven**
resolves https://github.com/iNavFlight/inav/issues/6427 and fixes:

1. Redundant code in  navigation_fw_launch.c  deleted.
2. Bug in  rth_estimator.c - wouldn't have picked up launch aborted prior to launch detection (aborted with stick movement when Launch set as Feature). This change is required now anyway due to the changes to the Launch code for 2.6.0 and the way launch detection is flagged after launch.

### CODE REVIEW

File: src/main/flight/rth_estimator.c [hunk 1]
```diff
@@ -153,7 +153,7 @@ static float calculateRemainingEnergyBeforeRTH(bool takeWindIntoAccount) {
           && feature(FEATURE_CURRENT_METER) && (batteryMetersConfig()->cruise_power > 0)
           && (currentBatteryProfile->capacity.unit == BAT_CAPACITY_UNIT_MWH) && (currentBatteryProfile->capacity.value > 0)
           && navigationPositionEstimateIsHealthy() && isImuHeadingValid() && (navConfig()->fw.cruise_speed > 0)
-          && ((!STATE(FIXED_WING_LEGACY)) || !isNavLaunchEnabled() || (isNavLaunchEnabled() && isFixedWingLaunchDetected()))
+          && ((!STATE(FIXED_WING_LEGACY)) || !isNavLaunchEnabled() || (isNavLaunchEnabled() && (isFixedWingLaunchDetected() || isFixedWingLaunchFinishedOrAborted())))
```
Comment (digitalentity) [inline src/main/flight/rth_estimator.c]: This needs clean-up. This whole logic condition is impossible to read.

Comment (breadoven) [reply src/main/flight/rth_estimator.c]: I agree, not not's are really confusing to get your head around. and it could be broken down into groups of criteria I'm also not sure why the launch stuff is in here anyway.  RTH estimator originally only worked if you used Nav Launch but it was changed to work without when I raised this as a problem if you didn't use Launch, and it still works fine. Does the short time between arming and launching really make enough of a difference to the estimation to require launch to be considered ?

Comment (breadoven) [reply src/main/flight/rth_estimator.c]: Is this clearer ?

```
static float calculateRemainingEnergyBeforeRTH(bool takeWindIntoAccount) {
    // Fixed wing only for now
    if (!(STATE(FIXED_WING_LEGACY) || ARMING_FLAG(ARMED))) {
        return -1;
    }
    
#ifdef USE_WIND_ESTIMATOR
    if (takeWindIntoAccount && !isEstimatedWindSpeedValid()) {
        return -1;
    }
#endif

    const bool batterySettingsAreOK = feature(FEATURE_VBAT) && feature(FEATURE_CURRENT_METER) && batteryWasFullWhenPluggedIn();
    const bool rthEstimatorSettingsAreOK = batteryMetersConfig()->cruise_power > 0 && currentBatteryProfile->capacity.unit == BAT_CAPACITY_UNIT_MWH &&currentBatteryProfile->capacity.value > 0 && navConfig()->fw.cruise_speed > 0; 
    const bool navigationIsOK = navigationPositionEstimateIsHealthy() && isImuHeadingValid();
    const bool launchIsActiveOrFinished = isNavLaunchEnabled() && (isFixedWingLaunchDetected() || isFixedWingLaunchFinishedOrAborted());
    
    if (!(batterySettingsAreOK && rthEstimatorSettingsAreOK && navigationIsOK && launchIsActiveOrFinished) {
        return -1;
    }
```

Comment (breadoven) [reply src/main/flight/rth_estimator.c]: Thinking this code would be better placed in calculateRemainingDistanceBeforeRTH which calls calculateRemainingEnergyBeforeRTH via another function. Why call 2 functions before checking if the criteria for it to work are met when you could check at the initial calling function and stop there if not ?

Comment (breadoven) [reply src/main/flight/rth_estimator.c]: Realised launchIsActiveOrFinished is wrong, should be the following instead:

`const bool launchIsInactiveOrDetected = !isNavLaunchEnabled() || (isFixedWingLaunchDetected() || isFixedWingLaunchFinishedOrAborted());`

Or just delete completely since it doesn't seem necessary anyway.

**Comment by avsaase** [comment]
Is this safe to test?

**Comment by breadoven** [comment]
Well the changes fix the issue with the flight timer and the RTH estimator still works as before so it should work OK.

**Comment by avsaase** [comment]
closes #6427

**Comment by breadoven** [comment]
Tried editing my original post @avsaase to auto close this but doesn't seem to work (I assume that's what you're trying to do).

Although at the moment this bug fix is yet to be approved together with a number of others. Would be useful to know why this is the case.

**Comment by avsaase** [comment]
@breadoven It seems the issue is now properly linked. I was trying to do it using the linked issue menu on the right but I couldn't find the issue there. 

I have flown with this PR for the past couple of months and all seems to work well, so I think this can be merged.
