### PR TITLE
Fix GHST telemetry

### LINKED ISSUE #6457: ghost protocol failsafe after ca. 4300s ontime
## Current Behavior
After ca 4300s ontime the flightcontroller goes into failsafe and does not comeback unless you reboot it.
I checked this several times on the bench.

In BF this does not happen, but bf resets the ontime to 0 after 4300s.
So i assume there is an overflow in a time relevated variable.

config dump: https://pastebin.com/rq3hWiSZ

# version
# INAV/MATEKF405 2.7.0 Dec 27 2020 / 16:20:50 (04e10aef)
# GCC-9.3.1 20200408 (release)

### PR DESCRIPTION
**Pull request by DzikuVx**
Fixes #6457

After overflow, telemetry was generated every 2ms instead of 100ms. That was slowly clogging serial port so failsafe was triggered.

@tonycake you might be interested in this one

### CODE REVIEW

**Comment by DzikuVx** [comment]
@Christoph-Hofmann you might want to take a look

**Comment by Christoph-Hofmann** [comment]
I checked your changes. It work now fine.
Now flight times with ghost longer than 4300s are possible 👍 
@DzikuVx Pawel you are my hero :-)

File: src/main/telemetry/ghst.c [hunk 1]
```diff
@@ -163,7 +163,7 @@ bool checkGhstTelemetryState(void)
 // Called periodically by the scheduler
  void handleGhstTelemetry(timeUs_t currentTimeUs)
 {
-    static uint32_t ghstLastCycleTime;
+    static timeUs_t ghstLastCycleTime;
```
Comment (digitalentity) [inline src/main/telemetry/ghst.c:166]: 32-bit microtime overflow, ta-daaah!

Comment (tonycake) [reply src/main/telemetry/ghst.c:166]: Nice Find! thanks to everyone involved in finding this, looks like it wasn't easy to find. 
So.. looking at the BF driver, I guess the behavior is different because timeUs_t is 32 bits in BF? 
At least I can't find anywhere that defines USE_64BIT_TIME.

Comment (digitalentity) [reply src/main/telemetry/ghst.c:166]: Yes, AFAIK BF is 32-bit only, therefore even if uint32_t overflows, this doesn't mess with scheduling because `uint32 - uint32` will always yield a correct result even if overflow happens.

Here it's different, after crossing the 2^32 boundary `uint64 - uint32` will always yield a result larger than 4294 seconds which causes the telemetry driver to think "Oh shit, I sent the last telemetry packet over 1 hour ago" and schedule the new one immediately.
